EjerciciosPropuestos1_Ticona/Controllers/Ejercicio03Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EjerciciosPropuestos1_Ticona.Models;

namespace EjerciciosPropuestos1_Ticona.Controllers
{
    public class Ejercicio03Controller : Controller
    {
        public int mayor, medio , menor , aux;

        // GET: Ejercicio03
        public ActionResult Index(ClsEjercicio03 ObjEjercicio03)
        {
            Random aleatorio = new Random();

            ObjEjercicio03.numero1 = aleatorio.Next(100);
            ObjEjercicio03.numero2 = aleatorio.Next(100);
            ObjEjercicio03.numero3 = aleatorio.Next(100);

            int[] num = new int[3];
            num[0] = ObjEjercicio03.numero1;
            num[1] = ObjEjercicio03.numero2;
            num[2] = ObjEjercicio03.numero3;

            mayor = num[0];
            menor = num[0];
           
            for (int i = 0; i < num.Length; i++) {
                if (num[i] < menor) {
                    menor = num[i];
                }
                else if (num[i] > mayor)
                 {
                    mayor = num[i];
                }
            }

            if (num[0]>= num[1]) {
                aux = num[1];
                num[1] = num[0];
                num[0] = aux;
            }
            if (num[1] >= num[2])
            {
                aux = num[2];
                num[2] = num[1];
                num[1] = aux;
            }
            if (num[0] >= num[1])
            {
                medio =num[0];
            }
            else {
                medio =num[1]; 
            }
            
            ObjEjercicio03.resultado = "El número mayor es : " + mayor + "  El número medio es : " + medio + "  El número menor es : " + menor;

            return View("Index",ObjEjercicio03);
        }
    }
}

EjerciciosPropuestos1_Ticona/Views/Ejercicio03/Index.cshtml
@model EjerciciosPropuestos1_Ticona.Models.ClsEjercicio03

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ejercicio-03</title>
    <link href="~/assets/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>
        <h2><b>Ejercicio 03</b></h2>
        <br />
        @using (Html.BeginForm("Index", "Ejercicio03", FormMethod.Post))
        {
            <p>
                Números aleatorios
            </p>

            if (Session["i"] == null)
            {
                Session["i"] = 1;
                <h3>? - ? - ?</h3>
            }
            else
            {
                <h3>@Model.numero1 - @Model.numero2 - @Model.numero3</h3>
            }
            <input type="submit" value="Calcular" />
        }
        <br />
        @Model.resultado;
    </div>
</body>
</html>